In [0]:
import tensorflow as tf

## **1. Example**

**tf.Variable과 tf.get_Variable의 차이점**


1.  tf.get_variable 이 기존 변수를 가진 변수를 그래프에서 가져 tf.get_variable 여부와 관계없이 tf.Variable 은 항상 새 변수를 만든다. 존재하지 않으면 새 변수를 만든다.
2.  tf.Variable 은 초기 값을 지정하도록 요구한다.
3. tf.Variable 은 변수를 만들기위한 기본 연산이며 get_variable 은 주로 가중치 공유에 사용된다.

In [0]:
# tf.Variable

s = tf.Variable(2, name="scalar") 
m = tf.Variable([[0, 1], [2, 3]], name="matrix") 
W = tf.Variable(tf.zeros([784,10]))

In [0]:
# tf.get_variable(name, shape, initializer)

s = tf.get_variable("scalar", initializer=tf.constant(2)) 
m = tf.get_variable("matrix", initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())

In [0]:
#실패

with tf.Session() as sess:
	print(sess.run(W))

In [5]:
#성공

#initializer를 사용해야 한다.
#모든 변수를 한번에 초기화하는 방법
with tf.Session() as sess:
	print(sess.run(tf.global_variables_initializer()))

None


In [7]:
#변수의 하위집합만 초기화
with tf.Session() as sess:
	print(sess.run(tf.variables_initializer([s, W])))

None


In [11]:
#단일 변수 초기화
W = tf.Variable(tf.zeros([700,10]))
with tf.Session() as sess:
  sess.run(W.initializer)
  print(W)
  print(W\8m.eval())	

<tf.Variable 'Variable_3:0' shape=(700, 10) dtype=float32_ref>
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## **2. tf.Variable.assign()**

해당 변수에 새로운 값을 할당할 수 있음

In [12]:
W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
	sess.run(W.initializer)
	print(W.eval())

10


In [15]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
  sess.run(W.initializer)
  sess.run(assign_op)
  print(W.eval())


100


In [17]:
# 오리지널 값이 2인 변수를 만든다
my_var = tf.Variable(2, name="my_var") 

# 원래 값에 2를 곱하고 my_var_times_two에 저장한다
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
	sess.run(my_var.initializer)
	print(sess.run(my_var_times_two))
	print(sess.run(my_var_times_two))
	print(sess.run(my_var_times_two))

4
8
16


In [20]:
my_var = tf.Variable(10)
with tf.Session() as sess:
	sess.run(my_var.initializer)
	
# 10씩 증가
	print(sess.run(my_var.assign_add(10)))
# 2씩 감소 
#  print(sess.run(my_var.assign_sub(2)))

20


In [21]:
W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))

print(sess1.run(W.assign_add(100)))
print(sess2.run(W.assign_sub(50))) 		

sess1.close()
sess2.close()


20
8
120
-42
