# `tf.placeholder` 

### Placeholders


A TF program often has 2 phases: 
1. Assemble a graph 
2. Use a session to execute operations in the graph.

⇒ Assemble the graph first without knowing the values needed for computation

Analogy:
Define the function f(x, y) = 2 * x + y without knowing value of x or y. 
x, y are placeholders for the actual values.

### Why placeholders?
We, or our clients, can later supply their own data when they need to execute the computation. 

### API_DOCS

*tf.placeholder(dtype, shape=None, name=None)*

- Args
    - `dtype`: The type of elements in the tensor to be fed. 
    - `shape`: The shape of the tensor to be fed (optional). If the shape is not specified, you can feed a tensor of any shape. 
    - `name`: A name for the operation (optional).
- Returns 
    - A `Tensor` that may be used as a handle for feeding a value, but not evaluated directly.
- Raises 
    - `RuntimeError`: if eager execution is enabled
- Eager Compatibility 
    Placeholders are not compatible with eager execution.


<p style="text-align:right">
    <i>API_DOCS (https://www.tensorflow.org/api_docs/python/tf/placeholder)</i>
</p>

In [1]:
import tensorflow as tf
# Graph execution examples
#tf.enable_eager_execution()

### Example 1

In [2]:
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

with tf.Session() as sess:
  print(sess.run(y))  # ERROR: will fail because x was not fed.

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [1024,1024]
	 [[{{node Placeholder}} = Placeholder[dtype=DT_FLOAT, shape=[1024,1024], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder', defined at:
  File "/Users/pakddo/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/pakddo/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/Users/pakddo/.pyenv/versions/3.6.5/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/Users/pakddo/.pyenv/versions/3.6.5/lib/python3.6/asyncio/base_events.py", line 1432, in _run_once
    handle._run()
  File "/Users/pakddo/.pyenv/versions/3.6.5/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 370, in dispatch_queue
    yield self.process_one()
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tornado/gen.py", line 346, in wrapper
    runner = Runner(result, future, yielded)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tornado/gen.py", line 1080, in __init__
    self.run()
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2817, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2843, in _run_cell
    return runner(coro)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3018, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3183, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6b0026e5f22d>", line 1, in <module>
    x = tf.placeholder(tf.float32, shape=(1024, 1024))
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1745, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5020, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/Users/pakddo/.pyenv/versions/3.6.5/envs/modu-tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [1024,1024]
	 [[{{node Placeholder}} = Placeholder[dtype=DT_FLOAT, shape=[1024,1024], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


### Example 1

In [3]:
import numpy as np
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

with tf.Session() as sess:
  rand_array = np.random.rand(1024, 1024)
  print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.

[[253.22192 254.91275 254.85379 ... 247.81882 254.89024 260.1842 ]
 [247.55745 247.31862 246.86536 ... 240.60658 250.46785 256.7175 ]
 [261.4311  261.04163 258.14508 ... 254.35393 261.82843 268.90512]
 ...
 [250.01859 247.82202 243.99187 ... 236.46419 250.11058 254.80414]
 [257.74283 260.96136 258.61795 ... 254.14604 263.5616  267.73907]
 [252.65991 259.4732  261.8231  ... 248.50124 260.43637 265.65918]]


*tf.placeholder(dtype, shape=None, name=None)*


In [4]:
# create a placeholder for a vector of 3 elements, type tf.float32
a = tf.placeholder(tf.float32, shape=[3])

b = tf.constant([5, 5, 5], tf.float32)

# use the placeholder as you would a constant or a variable
c = a + b  # short for tf.add(a, b)

In [5]:
with tf.Session() as sess:
    print(sess.run(c, feed_dict={a: [1, 2, 3]}))
    # the tensor a is the key, not the string ‘a’

[6. 7. 8.]


Quirk:
shape=None means that tensor of any shape will be accepted as value for placeholder.

shape=None is easy to construct graphs, but nightmarish for debugging

In [6]:
# create a placeholder of type float 32-bit, shape is a vector of 3 elements
a = tf.placeholder(tf.float32, shape=[3])

# create a constant of type float 32-bit, shape is a vector of 3 elements
b = tf.constant([5, 5, 5], tf.float32)

# use the placeholder as you would a constant or a variable
c = a + b  # Short for tf.add(a, b)

with tf.Session() as sess:
    print(sess.run(c, {a: [1, 2, 3]}))

[6. 7. 8.]


Quirk:
shape=None also breaks all following shape inference, which makes many ops not work because they expect certain rank.


You can feed_dict any feedable tensor.
Placeholder is just a way to indicate that something must be fed

tf.Graph.is_feedable(tensor) 
#True if and only if tensor is feedable.

In [7]:
list_of_values_for_a = [[10, 11, 12], [13, 14, 15]]

In [8]:
with tf.Session() as sess:
    for a_value in list_of_values_for_a:
        print(sess.run(c, {a: a_value}))

[15. 16. 17.]
[18. 19. 20.]


### Feeding values to TF ops

In [9]:
# create operations, tensors, etc (using the default graph)
a = tf.add(2, 5)
b = tf.multiply(a, 3)

with tf.Session() as sess:
    # compute the value of b given a is 15
    print(sess.run(b, feed_dict={a: 15}))

45
