# TF.Variable

In [1]:
import tensorflow as tf

In [2]:
#Create Variables with tf.Variable
#method1
s = tf.Variable(2, name="scalar")
m = tf.Variable([[0,1],[2,3]], name="matrix")
W = tf.Variable(tf.zeros(784,10))

In [3]:
#Create variables with tf.get_variable
#method2
s1 = tf.get_variable("scalar1", initializer=tf.constant(2))
m1 = tf.get_variable("matrix1", initializer=tf.constant([[0,1],[2,3]]))
W1 = tf.get_variable("big_matrix1", shape=(784,10), initializer=tf.zeros_initializer())

method1 보단 method2를 추천

In [5]:
with tf.Session() as sess:
    print(sess.run(W1)) # <- 오류 발생. 

FailedPreconditionError: Attempting to use uninitialized value big_matrix1
	 [[{{node _retval_big_matrix1_0_0}} = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](big_matrix1)]]

TF Variable을 사용하기 위해서는 초기화(initializer()를 호출 해야함)

In [7]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(W1))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# Variable Initializer 

## init all values 

In [8]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())