In [1]:
from __future__ import absolute_import, division, print_function
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)
# => tf.Tensor([[1 2]
#               [3 4]], shape=(2, 2), dtype=int32)



tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [3]:
# 브로드캐스팅을 지원합니다.
b = tf.add(a, 1)
print(b)
# => tf.Tensor([[2 3]
#               [4 5]], shape=(2, 2), dtype=int32)



tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [4]:
# 연산자 오버로딩을 지원합니다.
print(a * b)
# => tf.Tensor([[ 2  6]
#               [12 20]], shape=(2, 2), dtype=int32)



tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [5]:
# NumPy 값을 써봅시다.
import numpy as np

c = np.multiply(a, b)
print(c)
# => [[ 2  6]
#     [12 20]]



[[ 2  6]
 [12 20]]


In [6]:
# 텐서로부터 numpy 형태의 값 받기:
print(a.numpy())
# => [[1 2]
#     [3 4]]

[[1 2]
 [3 4]]
