In [28]:
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
a= tf.constant([2,2], name='a')
b = tf.constant([[0,1],[2,3]], name='b')

In [4]:
x= tf.multiply(a,b, name ='mul')
print(x)
#with tf.Session() as sess:
#    print(sess.run(x))

tf.Tensor(
[[0 2]
 [4 6]], shape=(2, 2), dtype=int32)


In [5]:
tf.zeros([2,3], tf.int32)

<tf.Tensor: id=8, shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [6]:
tf.fill([2,3], 8)

<tf.Tensor: id=12, shape=(2, 3), dtype=int32, numpy=
array([[8, 8, 8],
       [8, 8, 8]], dtype=int32)>

In [7]:
tf.lin_space(10.0, 13.0, 4)

<tf.Tensor: id=17, shape=(4,), dtype=float32, numpy=array([10., 11., 12., 13.], dtype=float32)>

In [8]:
tf.range(3,18,3)

<tf.Tensor: id=21, shape=(5,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15], dtype=int32)>

In [10]:
tf.div(b,a)


<tf.Tensor: id=31, shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [1, 1]], dtype=int32)>

In [11]:
tf.divide(b,a)

<tf.Tensor: id=35, shape=(2, 2), dtype=float64, numpy=
array([[0. , 0.5],
       [1. , 1.5]])>

In [12]:
tf.truediv(b,a)

<tf.Tensor: id=39, shape=(2, 2), dtype=float64, numpy=
array([[0. , 0.5],
       [1. , 1.5]])>

In [13]:
tf.floordiv(b,a)

<tf.Tensor: id=41, shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [1, 1]], dtype=int32)>

In [14]:
tf.realdiv(b,a)

InternalError: Could not find valid device for node.
Node: {{node RealDiv}} = RealDiv[T=DT_INT32](dummy_input, dummy_input)
All kernels registered for op RealDiv :
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
 [Op:RealDiv]

In [15]:
tf.truncatediv(b,a)

<tf.Tensor: id=43, shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [1, 1]], dtype=int32)>

In [16]:
tf.floor_div(b,a)

<tf.Tensor: id=45, shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [1, 1]], dtype=int32)>

In [17]:
t_1= ["a", "b", "c"]

In [18]:
tf.zeros_like(t_1)

<tf.Tensor: id=48, shape=(3,), dtype=string, numpy=array([b'', b'', b''], dtype=object)>

In [21]:
W= tf.Variable(tf.truncated_normal([700,10]))
W.initializer
print(W)

<tf.Variable 'Variable:0' shape=(700, 10) dtype=float32, numpy=
array([[ 1.8321801 , -1.5583957 ,  1.005805  , ...,  1.1110125 ,
        -1.1116982 ,  1.247057  ],
       [ 1.0431224 ,  1.0649478 ,  0.7950921 , ...,  0.01484907,
         0.93624926, -0.3932432 ],
       [-0.5014069 , -0.67107004, -0.55762494, ...,  1.1616085 ,
         0.74177414, -1.516535  ],
       ...,
       [-0.69072366,  0.07402413, -1.0511165 , ..., -0.7230082 ,
        -0.28894234,  0.35767263],
       [-0.5107774 ,  0.1791885 ,  0.15436856, ..., -0.16639465,
        -0.35322598, -0.4335129 ],
       [-0.42135188, -0.05672352, -0.9354532 , ...,  0.307038  ,
         0.02666545, -0.47134995]], dtype=float32)>


In [22]:
my_var = tf.Variable(10)
my_var.initializer
my_var.assign_add(10)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=20>

In [23]:
my_var.assign_add(20)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=40>

In [24]:
my_var.assign_sub(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=38>

In [3]:
# Placeholder
import tensorflow as tf


a= tf.placeholder(tf.float32, shape=[3])
b= tf.constant([5,5,5], tf.float32)
c= a+b

with tf.Session() as sess:
    print(sess.run(c, {a: [1,2,3]}))

[6. 7. 8.]
